# Vegetation v.s. No Vegetation

In [1]:
import numpy as np

In [2]:
trn_val_y=np.load('/data/DW/Challenge/GermanAIChallenge2018/Round_2/trn_val_y.npy')
trn_val_y.shape

(376485,)

In [19]:
trn_val_y

array([ 5, 16, 16, ...,  2,  7,  0])

In [36]:
building=np.where(trn_val_y<10)[0]
building

array([     0,      3,      4, ..., 376482, 376483, 376484])

In [23]:
building_veg=np.where(((trn_val_y>=3) & (trn_val_y<6)) | (trn_val_y==8))[0]
building_veg

array([     0,     14,     17, ..., 376462, 376465, 376477])

In [24]:
building_noveg=np.where((trn_val_y<3)|((trn_val_y>=6) & (trn_val_y<8)) | (trn_val_y==9))[0]
building_noveg

array([     3,      4,     10, ..., 376482, 376483, 376484])

In [25]:
print(building_veg.shape,building_noveg.shape)

(79444,) (124333,)


New label

In [26]:
label_ve=-np.ones(trn_val_y.shape)
label_ve[building_noveg]=0
label_ve[building_veg]=1

In [40]:
np.save('/data/DW/Challenge/GermanAIChallenge2018/Round_2/SmallClass/building_scheme1/NoVe_Ve/nove_ve_y.npy',label_ve)

In [41]:
label_ve

array([ 1., -1., -1., ...,  0.,  0.,  0.])

In [27]:
from sklearn.model_selection import StratifiedKFold

In [32]:
skf_ve = StratifiedKFold(n_splits=5,random_state=2019,shuffle=True)

In [30]:
X = np.load("/data/DW/Challenge/GermanAIChallenge2018/Round_2/R2trn_s1_new.npy")[building]
y = label_ve[building]

In [31]:
print(X.shape,y.shape)

(203777, 32, 32, 5) (203777,)


In [33]:
Building_vege_indexes=np.array(list(skf_ve.split(X, y)))

In [34]:
Building_vege_indexes

array([[array([     1,      2,      4, ..., 203773, 203774, 203775]),
        array([     0,      3,     10, ..., 203758, 203765, 203776])],
       [array([     0,      1,      2, ..., 203773, 203774, 203776]),
        array([     6,      7,     13, ..., 203767, 203771, 203775])],
       [array([     0,      2,      3, ..., 203774, 203775, 203776]),
        array([     1,      8,      9, ..., 203739, 203763, 203773])],
       [array([     0,      1,      2, ..., 203773, 203775, 203776]),
        array([     4,     16,     19, ..., 203768, 203772, 203774])],
       [array([     0,      1,      3, ..., 203774, 203775, 203776]),
        array([     2,      5,     11, ..., 203766, 203769, 203770])]],
      dtype=object)

In [37]:
B1_ve = []
B2_ve = []
B3_ve = []
B4_ve = []
B5_ve = []
B1_ve.append(building[Building_vege_indexes[0][0]])
B1_ve.append(building[Building_vege_indexes[0][1]])
B2_ve.append(building[Building_vege_indexes[1][0]])
B2_ve.append(building[Building_vege_indexes[1][1]])
B3_ve.append(building[Building_vege_indexes[2][0]])
B3_ve.append(building[Building_vege_indexes[2][1]])
B4_ve.append(building[Building_vege_indexes[3][0]])
B4_ve.append(building[Building_vege_indexes[3][1]])
B5_ve.append(building[Building_vege_indexes[4][0]])
B5_ve.append(building[Building_vege_indexes[4][1]])

In [38]:
B_ve =[]
B_ve.append(B1_ve)
B_ve.append(B2_ve)
B_ve.append(B3_ve)
B_ve.append(B4_ve)
B_ve.append(B5_ve)

In [43]:
Building_Ve_idx=np.array(B_ve)
Building_Ve_idx

array([[array([     3,      4,     13, ..., 376477, 376482, 376483]),
        array([     0,     10,     20, ..., 376446, 376462, 376484])],
       [array([     0,      3,      4, ..., 376477, 376482, 376484]),
        array([    16,     17,     26, ..., 376465, 376472, 376483])],
       [array([     0,      4,     10, ..., 376482, 376483, 376484]),
        array([     3,     18,     19, ..., 376412, 376458, 376477])],
       [array([     0,      3,      4, ..., 376477, 376483, 376484]),
        array([    13,     32,     35, ..., 376468, 376476, 376482])],
       [array([     0,      3,     10, ..., 376482, 376483, 376484]),
        array([     4,     14,     23, ..., 376464, 376469, 376470])]],
      dtype=object)

In [44]:
np.save('/data/DW/Challenge/GermanAIChallenge2018/Round_2/SmallClass/building_scheme1/NoVe_Ve/Building_Ve_Nove_idx.npy',Building_Ve_idx)

# Compact v.s. Other

In [86]:
import numpy as np

In [87]:
trn_val_y=np.load('/data/DW/Challenge/GermanAIChallenge2018/Round_2/trn_val_y.npy')
trn_val_y.shape

(376485,)

In [88]:
trn_val_y

array([ 5, 16, 16, ...,  2,  7,  0])

In [89]:
building_noveg=np.where((trn_val_y<3)|((trn_val_y>=6) & (trn_val_y<8)) | (trn_val_y==9))[0]
building_noveg

array([     3,      4,     10, ..., 376482, 376483, 376484])

In [90]:
building_noveg_comp=np.where(trn_val_y<3)[0]
building_noveg_comp

array([     3,     16,     18, ..., 376476, 376482, 376484])

In [91]:
building_noveg_other=np.where(((trn_val_y>=6) & (trn_val_y<8)) | (trn_val_y==9))[0]
building_noveg_other

array([     4,     10,     13, ..., 376469, 376472, 376483])

In [92]:
print(building_noveg_comp.shape,building_noveg_other.shape)

(65055,) (59278,)


New label

In [93]:
label_comp_other=-np.ones(trn_val_y.shape)
label_comp_other[building_noveg_comp]=0
label_comp_other[building_noveg_other]=1

In [94]:
label_comp_other

array([-1., -1., -1., ...,  0.,  1.,  0.])

In [95]:
np.save('/data/DW/Challenge/GermanAIChallenge2018/Round_2/SmallClass/building_scheme1/Comp_Other/comp_other_y.npy',label_comp_other)

In [96]:
from sklearn.model_selection import StratifiedKFold

In [97]:
skf_co_ot = StratifiedKFold(n_splits=5,random_state=2019,shuffle=True)

In [98]:
X = np.load("/data/DW/Challenge/GermanAIChallenge2018/Round_2/R2trn_s1_new.npy")[building_noveg]
y = label_comp_other[building_noveg]

In [99]:
print(X.shape,y.shape)

(124333, 32, 32, 5) (124333,)


In [100]:
np.unique(y)

array([0., 1.])

In [101]:
Building_nove_com_oth_indexes=np.array(list(skf_co_ot.split(X, y)))

In [102]:
Building_nove_com_oth_indexes

array([[array([     2,      3,      4, ..., 124329, 124331, 124332]),
        array([     0,      1,      8, ..., 124325, 124328, 124330])],
       [array([     0,      1,      2, ..., 124328, 124329, 124330]),
        array([     3,      5,      6, ..., 124327, 124331, 124332])],
       [array([     0,      1,      2, ..., 124330, 124331, 124332]),
        array([    13,     16,     18, ..., 124314, 124319, 124320])],
       [array([     0,      1,      3, ..., 124330, 124331, 124332]),
        array([     2,      4,     30, ..., 124322, 124323, 124329])],
       [array([     0,      1,      2, ..., 124330, 124331, 124332]),
        array([    10,     14,     43, ..., 124310, 124315, 124318])]],
      dtype=object)

In [103]:
B1_nove_com_oth = []
B2_nove_com_oth = []
B3_nove_com_oth = []
B4_nove_com_oth = []
B5_nove_com_oth = []
B1_nove_com_oth.append(building_noveg[Building_nove_com_oth_indexes[0][0]])
B1_nove_com_oth.append(building_noveg[Building_nove_com_oth_indexes[0][1]])
B2_nove_com_oth.append(building_noveg[Building_nove_com_oth_indexes[1][0]])
B2_nove_com_oth.append(building_noveg[Building_nove_com_oth_indexes[1][1]])
B3_nove_com_oth.append(building_noveg[Building_nove_com_oth_indexes[2][0]])
B3_nove_com_oth.append(building_noveg[Building_nove_com_oth_indexes[2][1]])
B4_nove_com_oth.append(building_noveg[Building_nove_com_oth_indexes[3][0]])
B4_nove_com_oth.append(building_noveg[Building_nove_com_oth_indexes[3][1]])
B5_nove_com_oth.append(building_noveg[Building_nove_com_oth_indexes[4][0]])
B5_nove_com_oth.append(building_noveg[Building_nove_com_oth_indexes[4][1]])

In [104]:
B_nove_com_oth =[]
B_nove_com_oth.append(B1_nove_com_oth)
B_nove_com_oth.append(B2_nove_com_oth)
B_nove_com_oth.append(B3_nove_com_oth)
B_nove_com_oth.append(B4_nove_com_oth)
B_nove_com_oth.append(B5_nove_com_oth)

In [105]:
Building_nove_com_oth_idx=np.array(B_nove_com_oth)
Building_nove_com_oth_idx

array([[array([    10,     13,     16, ..., 376476, 376483, 376484]),
        array([     3,      4,     30, ..., 376468, 376472, 376482])],
       [array([     3,      4,     10, ..., 376472, 376476, 376482]),
        array([    13,     18,     23, ..., 376470, 376483, 376484])],
       [array([     3,      4,     10, ..., 376482, 376483, 376484]),
        array([    41,     48,     56, ..., 376423, 376439, 376440])],
       [array([     3,      4,     13, ..., 376482, 376483, 376484]),
        array([    10,     16,     87, ..., 376446, 376461, 376476])],
       [array([     3,      4,     10, ..., 376482, 376483, 376484]),
        array([    35,     43,    135, ..., 376412, 376426, 376429])]],
      dtype=object)

In [106]:
np.save('/data/DW/Challenge/GermanAIChallenge2018/Round_2/SmallClass/building_scheme1/Comp_Other/Building_com_oth_idx.npy',Building_nove_com_oth_idx)

# Open v.s. Sparse

In [71]:
import numpy as np

In [72]:
trn_val_y=np.load('/data/DW/Challenge/GermanAIChallenge2018/Round_2/trn_val_y.npy')
trn_val_y.shape

(376485,)

In [73]:
trn_val_y

array([ 5, 16, 16, ...,  2,  7,  0])

In [107]:
building_veg=np.where(((trn_val_y>=3) & (trn_val_y<6)) | (trn_val_y==8))[0]
building_veg

array([     0,     14,     17, ..., 376462, 376465, 376477])

In [108]:
building_veg_open=np.where((trn_val_y>=3) & (trn_val_y<6))[0]
building_veg_open

array([     0,     17,     19, ..., 376457, 376458, 376462])

In [109]:
building_veg_sparse=np.where(trn_val_y==8)[0]
building_veg_sparse

array([    14,     20,     25, ..., 376435, 376465, 376477])

In [110]:
print(building_veg_open.shape,building_veg_sparse.shape)

(63946,) (15498,)


New label

In [111]:
label_open_spar=-np.ones(trn_val_y.shape)
label_open_spar[building_veg_open]=0
label_open_spar[building_veg_sparse]=1

In [112]:
label_open_spar

array([ 0., -1., -1., ..., -1., -1., -1.])

In [113]:
np.save('/data/DW/Challenge/GermanAIChallenge2018/Round_2/SmallClass/building_scheme1/Open_Sparse/open_spar_y.npy',label_open_spar)  

In [114]:
from sklearn.model_selection import StratifiedKFold

In [115]:
skf_op_sp = StratifiedKFold(n_splits=5,random_state=2019,shuffle=True)

In [116]:
X = np.load("/data/DW/Challenge/GermanAIChallenge2018/Round_2/R2trn_s1_new.npy")[building_veg]
y = label_open_spar[building_veg]

In [117]:
print(X.shape,y.shape)

(79444, 32, 32, 5) (79444,)


In [118]:
np.unique(y)

array([0., 1.])

In [119]:
Building_ve_ope_spa_indexes=np.array(list(skf_op_sp.split(X, y)))

In [121]:
Building_ve_ope_spa_indexes

array([[array([    1,     2,     3, ..., 79437, 79438, 79443]),
        array([    0,     5,     8, ..., 79440, 79441, 79442])],
       [array([    0,     1,     2, ..., 79441, 79442, 79443]),
        array([    3,     6,     7, ..., 79435, 79437, 79438])],
       [array([    0,     2,     3, ..., 79440, 79441, 79442]),
        array([    1,     4,     9, ..., 79423, 79431, 79443])],
       [array([    0,     1,     3, ..., 79441, 79442, 79443]),
        array([    2,    23,    26, ..., 79424, 79433, 79436])],
       [array([    0,     1,     2, ..., 79441, 79442, 79443]),
        array([   10,    30,    33, ..., 79425, 79427, 79434])]],
      dtype=object)

In [122]:
B1_ve_ope_spa = []
B2_ve_ope_spa = []
B3_ve_ope_spa = []
B4_ve_ope_spa = []
B5_ve_ope_spa = []
B1_ve_ope_spa.append(building_veg[Building_ve_ope_spa_indexes[0][0]])
B1_ve_ope_spa.append(building_veg[Building_ve_ope_spa_indexes[0][1]])
B2_ve_ope_spa.append(building_veg[Building_ve_ope_spa_indexes[1][0]])
B2_ve_ope_spa.append(building_veg[Building_ve_ope_spa_indexes[1][1]])
B3_ve_ope_spa.append(building_veg[Building_ve_ope_spa_indexes[2][0]])
B3_ve_ope_spa.append(building_veg[Building_ve_ope_spa_indexes[2][1]])
B4_ve_ope_spa.append(building_veg[Building_ve_ope_spa_indexes[3][0]])
B4_ve_ope_spa.append(building_veg[Building_ve_ope_spa_indexes[3][1]])
B5_ve_ope_spa.append(building_veg[Building_ve_ope_spa_indexes[4][0]])
B5_ve_ope_spa.append(building_veg[Building_ve_ope_spa_indexes[4][1]])

In [124]:
B_ve_ope_spa =[]
B_ve_ope_spa.append(B1_ve_ope_spa)
B_ve_ope_spa.append(B2_ve_ope_spa)
B_ve_ope_spa.append(B3_ve_ope_spa)
B_ve_ope_spa.append(B4_ve_ope_spa)
B_ve_ope_spa.append(B5_ve_ope_spa)

In [125]:
Building_ve_ope_sta_idx=np.array(B_ve_ope_spa)
Building_ve_ope_sta_idx

array([[array([    14,     17,     19, ..., 376451, 376455, 376477]),
        array([     0,     25,     33, ..., 376458, 376462, 376465])],
       [array([     0,     14,     17, ..., 376462, 376465, 376477]),
        array([    19,     27,     32, ..., 376445, 376451, 376455])],
       [array([     0,     17,     19, ..., 376458, 376462, 376465]),
        array([    14,     20,     37, ..., 376378, 376419, 376477])],
       [array([     0,     14,     19, ..., 376462, 376465, 376477]),
        array([    17,    111,    126, ..., 376385, 376424, 376448])],
       [array([     0,     14,     17, ..., 376462, 376465, 376477]),
        array([    46,    142,    149, ..., 376388, 376406, 376435])]],
      dtype=object)

In [126]:
np.save('/data/DW/Challenge/GermanAIChallenge2018/Round_2/SmallClass/building_scheme1/Open_Sparse/Building_ope_sta_idx.npy',Building_ve_ope_sta_idx) 

# Compact

In [127]:
import numpy as np

In [128]:
trn_val_y=np.load('/data/DW/Challenge/GermanAIChallenge2018/Round_2/trn_val_y.npy')
trn_val_y.shape

(376485,)

In [129]:
trn_val_y

array([ 5, 16, 16, ...,  2,  7,  0])

In [131]:
building_comp=np.where(trn_val_y<3)[0]
building_comp

array([     3,     16,     18, ..., 376476, 376482, 376484])

New Label

In [132]:
label_comp=-np.ones(trn_val_y.shape)
label_comp[building_comp]=trn_val_y[building_comp]

In [133]:
label_comp

array([-1., -1., -1., ...,  2., -1.,  0.])

In [134]:
np.save('/data/DW/Challenge/GermanAIChallenge2018/Round_2/SmallClass/building_scheme1/Compact/comp_y.npy',label_comp)

In [135]:
from sklearn.model_selection import StratifiedKFold

In [136]:
skf_comp = StratifiedKFold(n_splits=5,random_state=2019,shuffle=True)

In [137]:
X = np.load("/data/DW/Challenge/GermanAIChallenge2018/Round_2/R2trn_s1_new.npy")[building_comp]
y = label_comp[building_comp]

In [138]:
print(X.shape,y.shape)

(65055, 32, 32, 5) (65055,)


In [139]:
np.unique(y)

array([0., 1., 2.])

In [140]:
Building_comp_indexes=np.array(list(skf_comp.split(X, y)))

In [141]:
Building_comp_indexes

array([[array([    0,     1,     3, ..., 65048, 65049, 65052]),
        array([    2,     6,     7, ..., 65051, 65053, 65054])],
       [array([    0,     2,     3, ..., 65051, 65053, 65054]),
        array([    1,     5,    10, ..., 65043, 65049, 65052])],
       [array([    0,     1,     2, ..., 65052, 65053, 65054]),
        array([    4,     8,    25, ..., 65038, 65045, 65047])],
       [array([    1,     2,     4, ..., 65052, 65053, 65054]),
        array([    0,     3,     9, ..., 65029, 65034, 65041])],
       [array([    0,     1,     2, ..., 65052, 65053, 65054]),
        array([   12,    15,    26, ..., 65044, 65046, 65048])]],
      dtype=object)

In [142]:
B1_comp = []
B2_comp = []
B3_comp = []
B4_comp = []
B5_comp = []
B1_comp.append(building_comp[Building_comp_indexes[0][0]])
B1_comp.append(building_comp[Building_comp_indexes[0][1]])
B2_comp.append(building_comp[Building_comp_indexes[1][0]])
B2_comp.append(building_comp[Building_comp_indexes[1][1]])
B3_comp.append(building_comp[Building_comp_indexes[2][0]])
B3_comp.append(building_comp[Building_comp_indexes[2][1]])
B4_comp.append(building_comp[Building_comp_indexes[3][0]])
B4_comp.append(building_comp[Building_comp_indexes[3][1]])
B5_comp.append(building_comp[Building_comp_indexes[4][0]])
B5_comp.append(building_comp[Building_comp_indexes[4][1]])

In [143]:
B_comp =[]
B_comp.append(B1_comp)
B_comp.append(B2_comp)
B_comp.append(B3_comp)
B_comp.append(B4_comp)
B_comp.append(B5_comp)

In [144]:
Building_comp_idx=np.array(B_comp)
Building_comp_idx

array([[array([     3,     16,     34, ..., 376439, 376461, 376476]),
        array([    18,     43,     48, ..., 376470, 376482, 376484])],
       [array([     3,     18,     34, ..., 376470, 376482, 376484]),
        array([    16,     38,     57, ..., 376390, 376461, 376476])],
       [array([     3,     16,     18, ..., 376476, 376482, 376484]),
        array([    36,     49,    136, ..., 376358, 376412, 376421])],
       [array([    16,     18,     36, ..., 376476, 376482, 376484]),
        array([     3,     34,     56, ..., 376322, 376343, 376381])],
       [array([     3,     16,     18, ..., 376476, 376482, 376484]),
        array([    67,     83,    137, ..., 376395, 376418, 376439])]],
      dtype=object)

In [145]:
np.save('/data/DW/Challenge/GermanAIChallenge2018/Round_2/SmallClass/building_scheme1/Compact/Building_comp_idx.npy',Building_comp_idx)

# Other

In [146]:
import numpy as np

In [147]:
trn_val_y=np.load('/data/DW/Challenge/GermanAIChallenge2018/Round_2/trn_val_y.npy')
trn_val_y.shape

(376485,)

In [148]:
trn_val_y

array([ 5, 16, 16, ...,  2,  7,  0])

In [149]:
building_other=np.where(((trn_val_y>=6) & (trn_val_y<8)) | (trn_val_y==9))[0]
building_other

array([     4,     10,     13, ..., 376469, 376472, 376483])

New Label

In [150]:
label_other=-np.ones(trn_val_y.shape)

label_other[np.where(trn_val_y==6)[0]]=0
label_other[np.where(trn_val_y==7)[0]]=1
label_other[np.where(trn_val_y==9)[0]]=2

In [152]:
label_other

array([-1., -1., -1., ..., -1.,  1., -1.])

In [153]:
np.save('/data/DW/Challenge/GermanAIChallenge2018/Round_2/SmallClass/building_scheme1/Other/other_y.npy',label_other)

In [154]:
from sklearn.model_selection import StratifiedKFold

In [155]:
skf_other = StratifiedKFold(n_splits=5,random_state=2019,shuffle=True)

In [159]:
X = np.load("/data/DW/Challenge/GermanAIChallenge2018/Round_2/R2trn_s1_new.npy")[building_other]
y = label_other[building_other]

In [160]:
print(X.shape,y.shape)

(59278, 32, 32, 5) (59278,)


In [161]:
np.unique(y)

array([0., 1., 2.])

In [162]:
Building_other_indexes=np.array(list(skf_other.split(X, y)))

In [164]:
Building_other_indexes

array([[array([    0,     1,     2, ..., 59274, 59276, 59277]),
        array([    3,     4,     7, ..., 59268, 59269, 59275])],
       [array([    1,     2,     3, ..., 59275, 59276, 59277]),
        array([    0,     6,     9, ..., 59264, 59271, 59273])],
       [array([    0,     1,     2, ..., 59274, 59275, 59277]),
        array([    5,    21,    27, ..., 59256, 59266, 59276])],
       [array([    0,     3,     4, ..., 59273, 59275, 59276]),
        array([    1,     2,    25, ..., 59272, 59274, 59277])],
       [array([    0,     1,     2, ..., 59275, 59276, 59277]),
        array([    8,    26,    35, ..., 59260, 59267, 59270])]],
      dtype=object)

In [165]:
B1_other = []
B2_other = []
B3_other = []
B4_other = []
B5_other = []
B1_other.append(building_other[Building_other_indexes[0][0]])
B1_other.append(building_other[Building_other_indexes[0][1]])
B2_other.append(building_other[Building_other_indexes[1][0]])
B2_other.append(building_other[Building_other_indexes[1][1]])
B3_other.append(building_other[Building_other_indexes[2][0]])
B3_other.append(building_other[Building_other_indexes[2][1]])
B4_other.append(building_other[Building_other_indexes[3][0]])
B4_other.append(building_other[Building_other_indexes[3][1]])
B5_other.append(building_other[Building_other_indexes[4][0]])
B5_other.append(building_other[Building_other_indexes[4][1]])

In [166]:
B_other =[]
B_other.append(B1_other)
B_other.append(B2_other)
B_other.append(B3_other)
B_other.append(B4_other)
B_other.append(B5_other)

In [167]:
Building_other_idx=np.array(B_other)
Building_other_idx

array([[array([     4,     10,     13, ..., 376468, 376472, 376483]),
        array([    23,     26,     41, ..., 376427, 376428, 376469])],
       [array([    10,     13,     23, ..., 376469, 376472, 376483]),
        array([     4,     35,     60, ..., 376405, 376440, 376446])],
       [array([     4,     10,     13, ..., 376468, 376469, 376483]),
        array([    30,    152,    193, ..., 376383, 376423, 376472])],
       [array([     4,     23,     26, ..., 376446, 376469, 376472]),
        array([    10,     13,    174, ..., 376443, 376468, 376483])],
       [array([     4,     10,     13, ..., 376469, 376472, 376483]),
        array([    44,    190,    241, ..., 376394, 376426, 376429])]],
      dtype=object)

In [168]:
np.save('/data/DW/Challenge/GermanAIChallenge2018/Round_2/SmallClass/building_scheme1/Other/Building_other_idx.npy',Building_other_idx)

# Open

In [169]:
import numpy as np

In [170]:
trn_val_y=np.load('/data/DW/Challenge/GermanAIChallenge2018/Round_2/trn_val_y.npy')
trn_val_y.shape

(376485,)

In [171]:
trn_val_y

array([ 5, 16, 16, ...,  2,  7,  0])

In [172]:
building_open=np.where((trn_val_y>=3) & (trn_val_y<6))[0]
building_open

array([     0,     17,     19, ..., 376457, 376458, 376462])

New Label

In [173]:
label_open=-np.ones(trn_val_y.shape)

label_open[building_open]=trn_val_y[building_open]-3

In [174]:
label_open

array([ 2., -1., -1., ..., -1., -1., -1.])

In [175]:
np.save('/data/DW/Challenge/GermanAIChallenge2018/Round_2/SmallClass/building_scheme1/Open/open_y.npy',label_open)

In [176]:
from sklearn.model_selection import StratifiedKFold

In [177]:
skf_open = StratifiedKFold(n_splits=5,random_state=2019,shuffle=True)

In [179]:
X = np.load("/data/DW/Challenge/GermanAIChallenge2018/Round_2/R2trn_s1_new.npy")[building_open]
y = label_open[building_open]

In [180]:
print(X.shape,y.shape)

(63946, 32, 32, 5) (63946,)


In [181]:
np.unique(y)

array([0., 1., 2.])

In [182]:
Building_open_indexes=np.array(list(skf_open.split(X, y)))

In [183]:
Building_open_indexes

array([[array([    0,     1,     2, ..., 63940, 63941, 63942]),
        array([    5,     7,     9, ..., 63943, 63944, 63945])],
       [array([    0,     1,     2, ..., 63943, 63944, 63945]),
        array([    4,     6,    15, ..., 63927, 63932, 63938])],
       [array([    0,     4,     5, ..., 63943, 63944, 63945]),
        array([    1,     2,     3, ..., 63931, 63935, 63937])],
       [array([    1,     2,     3, ..., 63943, 63944, 63945]),
        array([    0,    21,    27, ..., 63936, 63940, 63942])],
       [array([    0,     1,     2, ..., 63943, 63944, 63945]),
        array([    8,    12,    17, ..., 63934, 63939, 63941])]],
      dtype=object)

In [184]:
B1_open = []
B2_open = []
B3_open = []
B4_open = []
B5_open = []
B1_open.append(building_open[Building_open_indexes[0][0]])
B1_open.append(building_open[Building_open_indexes[0][1]])
B2_open.append(building_open[Building_open_indexes[1][0]])
B2_open.append(building_open[Building_open_indexes[1][1]])
B3_open.append(building_open[Building_open_indexes[2][0]])
B3_open.append(building_open[Building_open_indexes[2][1]])
B4_open.append(building_open[Building_open_indexes[3][0]])
B4_open.append(building_open[Building_open_indexes[3][1]])
B5_open.append(building_open[Building_open_indexes[4][0]])
B5_open.append(building_open[Building_open_indexes[4][1]])

In [185]:
B_open =[]
B_open.append(B1_open)
B_open.append(B2_open)
B_open.append(B3_open)
B_open.append(B4_open)
B_open.append(B5_open)

In [186]:
Building_open_idx=np.array(B_open)
Building_open_idx

array([[array([     0,     17,     19, ..., 376448, 376451, 376455]),
        array([    33,     55,     63, ..., 376457, 376458, 376462])],
       [array([     0,     17,     19, ..., 376457, 376458, 376462]),
        array([    32,     46,     97, ..., 376290, 376352, 376422])],
       [array([     0,     32,     33, ..., 376457, 376458, 376462]),
        array([    17,     19,     27, ..., 376336, 376378, 376419])],
       [array([    17,     19,     27, ..., 376457, 376458, 376462]),
        array([     0,    126,    149, ..., 376406, 376448, 376455])],
       [array([     0,     17,     19, ..., 376457, 376458, 376462]),
        array([    59,     79,    108, ..., 376375, 376445, 376451])]],
      dtype=object)

In [187]:
np.save('/data/DW/Challenge/GermanAIChallenge2018/Round_2/SmallClass/building_scheme1/Open/Building_open_idx.npy',Building_open_idx) 