In [1]:
import numpy as np

In [2]:
Labels = np.load("trn_val_y.npy")
Labels.shape

(376485,)

In [3]:
Plants =  np.where((Labels >=10)&(Labels<14))[0]
Bare = np.where((Labels >=14)&(Labels<16))[0]

In [4]:
Plants

array([     5,      7,      9, ..., 376479, 376480, 376481])

In [5]:
Bare

array([    39,     50,     78, ..., 376441, 376474, 376475])

In [7]:
np.save("Plants_idx.npy",Plants)
np.save("Bare_idx.npy",Bare)

In [8]:
from sklearn.model_selection import StratifiedKFold

In [9]:
skf_Plants = StratifiedKFold(n_splits=5,random_state=2020,shuffle=True)
skf_Bare = StratifiedKFold(n_splits=5,random_state=2021,shuffle=True)

In [10]:
X_Plants = np.load("R2trn_s1_new.npy")[Plants]
y_Plants= Labels[Plants]
X_Bare= np.load("R2trn_s1_new.npy")[Bare]
y_Bare = Labels[Bare]

In [19]:
Plants_folds_indexes=np.array(list(skf_Plants.split(X_Plants, y_Plants)))
Bare_folds_indexes=np.array(list(skf_Bare.split(X_Bare, y_Bare)))

In [20]:
P1=[]
P2 = []
P3 = []
P4 = []
P5 = []
P1.append(Plants[Plants_folds_indexes[0][0]])
P1.append(Plants[Plants_folds_indexes[0][1]])
P2.append(Plants[Plants_folds_indexes[1][0]])
P2.append(Plants[Plants_folds_indexes[1][1]])
P3.append(Plants[Plants_folds_indexes[2][0]])
P3.append(Plants[Plants_folds_indexes[2][1]])
P4.append(Plants[Plants_folds_indexes[3][0]])
P4.append(Plants[Plants_folds_indexes[3][1]])
P5.append(Plants[Plants_folds_indexes[4][0]])
P5.append(Plants[Plants_folds_indexes[4][1]])

In [21]:
P =[]
P.append(P1)
P.append(P2)
P.append(P3)
P.append(P4)
P.append(P5)

In [23]:
Plants_Kfold_idx=np.array(P)
Plants_Kfold_idx

array([[array([     5,      7,      9, ..., 376479, 376480, 376481]),
        array([    15,     29,     31, ..., 376447, 376456, 376459])],
       [array([     5,      7,      9, ..., 376467, 376471, 376480]),
        array([   109,    112,    124, ..., 376478, 376479, 376481])],
       [array([     5,      7,      9, ..., 376478, 376479, 376481]),
        array([   117,    120,    122, ..., 376453, 376466, 376480])],
       [array([    15,     29,     31, ..., 376479, 376480, 376481]),
        array([     5,      7,      9, ..., 376454, 376463, 376471])],
       [array([     5,      7,      9, ..., 376479, 376480, 376481]),
        array([    54,     61,     75, ..., 376449, 376460, 376467])]],
      dtype=object)

In [24]:
B1=[]
B2 = []
B3 = []
B4 = []
B5 = []
B1.append(Bare[Bare_folds_indexes[0][0]])
B1.append(Bare[Bare_folds_indexes[0][1]])
B2.append(Bare[Bare_folds_indexes[1][0]])
B2.append(Bare[Bare_folds_indexes[1][1]])
B3.append(Bare[Bare_folds_indexes[2][0]])
B3.append(Bare[Bare_folds_indexes[2][1]])
B4.append(Bare[Bare_folds_indexes[3][0]])
B4.append(Bare[Bare_folds_indexes[3][1]])
B5.append(Bare[Bare_folds_indexes[4][0]])
B5.append(Bare[Bare_folds_indexes[4][1]])

B =[]
B.append(B1)
B.append(B2)
B.append(B3)
B.append(B4)
B.append(B5)

Bare_Kfold_idx=np.array(B)
Bare_Kfold_idx

array([[array([    39,    103,    260, ..., 376432, 376441, 376474]),
        array([    50,     78,    447, ..., 376099, 376206, 376475])],
       [array([    39,     50,     78, ..., 376441, 376474, 376475]),
        array([   463,    524,    626, ..., 376242, 376282, 376367])],
       [array([    39,     50,     78, ..., 376441, 376474, 376475]),
        array([   260,    336,    370, ..., 375860, 376265, 376269])],
       [array([    50,     78,    103, ..., 376367, 376432, 376475]),
        array([    39,    516,    530, ..., 376244, 376441, 376474])],
       [array([    39,     50,     78, ..., 376441, 376474, 376475]),
        array([   103,    661,    927, ..., 375901, 375912, 376432])]],
      dtype=object)

In [25]:
np.save("Plants_Kfold_idx.npy",Plants_Kfold_idx)
np.save("Bare_Kfold_idx.npy",Bare_Kfold_idx)

In [26]:
Bare.shape

(11164,)

In [27]:
Bare_Kfold_idx[0][0].shape

(8931,)

In [28]:
Bare_Kfold_idx[0][1].shape

(2233,)

In [30]:
Plants.shape

(109576,)

In [31]:
Plants_Kfold_idx[0][0].shape

(87659,)

In [32]:
Plants_Kfold_idx[0][1].shape

(21917,)

In [34]:
w = np.where(Labels ==16)[0]

In [35]:
w.shape

(51968,)