In [142]:
import numpy as np

In [143]:
Labels = np.load("trn_val_y.npy")
Labels.shape

(376485,)

In [144]:
Labels[:10]

array([ 5, 16, 16,  1,  7, 13, 16, 12, 16, 13])

In [145]:
Building = np.where(Labels <10)[0]
Plants =  np.where((Labels >=10)&(Labels<14))[0]
Bare = np.where((Labels >=14)&(Labels<16))[0]

In [146]:
Building

array([     0,      3,      4, ..., 376482, 376483, 376484])

In [147]:
Plants

array([     5,      7,      9, ..., 376479, 376480, 376481])

In [148]:
np.save("Building_idx.npy",Building)
np.save("Plants_idx.npy",Plants)

In [149]:
np.save("Bare_idx.npy",Bare)

In [150]:
Bare

array([    39,     50,     78, ..., 376441, 376474, 376475])

In [151]:
Bare.shape

(11164,)

In [152]:
from sklearn.model_selection import StratifiedKFold

In [153]:
skf = StratifiedKFold(n_splits=5,random_state=2019,shuffle=True)

In [154]:
X = np.load("R2trn_s1_new.npy")[Building]
y = Labels[Building]

In [155]:
y

array([5, 1, 7, ..., 2, 7, 0])

In [156]:
y.shape

(203777,)

In [157]:
Building_folds_indexes=np.array(list(skf.split(X, y)))

In [158]:
Building_folds_indexes[0][0].shape

(163018,)

In [159]:
Building_folds_indexes[0][1].shape

(40759,)

In [160]:
a = np.concatenate((Building_folds_indexes[0][0],Building_folds_indexes[0][1]),axis=0)

In [161]:
a[:30]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  9, 10, 14, 15, 16, 18, 19, 20, 21,
       22, 25, 26, 28, 30, 31, 32, 33, 38, 39, 40, 42, 44])

In [162]:
a.shape

(203777,)

In [163]:
Building.shape

(203777,)

In [164]:
Building[Building_folds_indexes[0][0]]

array([     0,      3,      4, ..., 376476, 376477, 376483])

In [165]:
Building[Building_folds_indexes[0][1]]

array([    18,     23,     25, ..., 376470, 376482, 376484])

In [166]:
B1=[]
B2 = []
B3 = []
B4 = []
B5 = []
B1.append(Building[Building_folds_indexes[0][0]])
B1.append(Building[Building_folds_indexes[0][1]])
B2.append(Building[Building_folds_indexes[1][0]])
B2.append(Building[Building_folds_indexes[1][1]])
B3.append(Building[Building_folds_indexes[2][0]])
B3.append(Building[Building_folds_indexes[2][1]])
B4.append(Building[Building_folds_indexes[3][0]])
B4.append(Building[Building_folds_indexes[3][1]])
B5.append(Building[Building_folds_indexes[4][0]])
B5.append(Building[Building_folds_indexes[4][1]])

In [167]:
B =[]
B.append(B1)
B.append(B2)
B.append(B3)
B.append(B4)
B.append(B5)

In [168]:
Building_Kfold_idx=np.array(B)

In [169]:
Building_Kfold_idx

array([[array([     0,      3,      4, ..., 376476, 376477, 376483]),
        array([    18,     23,     25, ..., 376470, 376482, 376484])],
       [array([     0,      3,     10, ..., 376482, 376483, 376484]),
        array([     4,     16,     32, ..., 376446, 376461, 376476])],
       [array([     0,      3,      4, ..., 376482, 376483, 376484]),
        array([    14,     17,     19, ..., 376423, 376472, 376477])],
       [array([     4,     14,     16, ..., 376477, 376482, 376484]),
        array([     0,      3,     10, ..., 376455, 376468, 376483])],
       [array([     0,      3,      4, ..., 376482, 376483, 376484]),
        array([    44,     59,     67, ..., 376439, 376445, 376451])]],
      dtype=object)

In [170]:
np.save("Building_Kfold_idx.npy",Building_Kfold_idx)