In [1]:
import numpy as np

## Largest Classes

In [2]:
Large=np.load("/data/DW/Challenge/GermanAIChallenge2018/Round_2/SmallClass/LargeClass/R2_predb_single_optionB_Large_Res50_epoch30_fold1_0212_soft_dehaze_nos1.npy")

In [3]:
print(Large.shape)

(4835,)


Building

In [4]:
Building_idx=np.where(Large==0)[0]
print(Building_idx.shape)

(2944,)


Plant

In [5]:
Plant_idx=np.where(Large==1)[0]
print(Plant_idx.shape)

(1212,)


Bare

In [6]:
Bare_idx=np.where(Large==2)[0]
print(Bare_idx.shape)

(179,)


Water

In [7]:
Water_idx=np.where(Large==3)[0]
print(Water_idx.shape)

(500,)


## Plant

In [8]:
pred_plant=np.load("/data/DW/Challenge/GermanAIChallenge2018/Round_2/SmallClass/R2_predb_single_optionB_plant_Res50_epoch48_fold1_0212_soft_dehaze_nos1.npy")
print(pred_plant.shape)

(4835,)


In [9]:
pred_plant_labeled=pred_plant+10

Ultimate Result

In [10]:
Result=-np.ones(Large.shape)

In [11]:
Result[Plant_idx]=pred_plant_labeled[Plant_idx]

## Bare

In [12]:
pred_bare=np.load("/data/DW/Challenge/GermanAIChallenge2018/Round_2/SmallClass/R2_predb_single_optionB_bare_Res50_epoch33_fold1_0212_soft_dehaze_nos1.npy")
print(pred_bare.shape)

(4835,)


In [13]:
pred_bare_labeled=pred_bare+14

In [14]:
Result[Bare_idx]=pred_bare_labeled[Bare_idx]

In [15]:
np.unique(Result)

array([-1., 10., 11., 12., 13., 14., 15.])

## Water

In [16]:
Result[Water_idx]=16

In [17]:
np.unique(Result)

array([-1., 10., 11., 12., 13., 14., 15., 16.])

## Building(straight)

In [18]:
pred_building=np.load("/data/DW/Challenge/GermanAIChallenge2018/Round_2/SmallClass/single_building_model/R2_predb_single_optionB_building_Res50_epoch129_fold1_0212_soft_dehaze_nos1.npy")
print(pred_building.shape)

(4835,)


In [19]:
Result[Building_idx]=pred_building[Building_idx]

In [20]:
np.unique(Result)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16.])

## Save

In [21]:
import torch

In [22]:
def write_csv(results,file_name):
    import csv
    with open(file_name,'w') as f:
        writer = csv.writer(f)
        #writer.writerow(['id','label'])
        writer.writerows(results)#注意读写

#from keras.utils import to_categorical
#result = to_categorical(np.array(pred_y))


label=torch.from_numpy(Result[:,np.newaxis]).long()
print(label.shape)
one_hot=torch.zeros(len(Result), 17).scatter_(1, label, 1)
write_csv(one_hot.numpy().astype(int),'R2_predb_LSClass_single_optionB_Res50_0212_soft_straight_dehaze_nos1.csv')

torch.Size([4835, 1])


## Building

### Nove_Ve

In [18]:
Nove_Ve=np.load("/data/DW/Challenge/GermanAIChallenge2018/Round_2/SmallClass/building_scheme1/NoVe_Ve/R2_preda_single_optionB_building_nove_ve_Res50_epoch70_fold1_0210_soft_nos1.npy")
np.unique(Nove_Ve)

array([0, 1])

In [19]:
Building_Nove_idx=Building_idx[np.where(Nove_Ve[Building_idx]==0)[0]]
Building_Nove_idx.shape

(1807,)

In [20]:
Building_Ve_idx=Building_idx[np.where(Nove_Ve[Building_idx]==1)[0]]
Building_Ve_idx.shape

(1147,)

### Comp_Other

In [21]:
Comp_Other=np.load("/data/DW/Challenge/GermanAIChallenge2018/Round_2/SmallClass/building_scheme1/Comp_Other/R2_preda_single_optionB_building_comp_other_Res50_epoch45_fold1_0210_soft_nos1.npy")
np.unique(Comp_Other)

array([0, 1])

In [22]:
Building_Comp_idx=Building_Nove_idx[np.where(Comp_Other[Building_Nove_idx]==0)[0]]
Building_Comp_idx.shape

(778,)

In [23]:
Building_Other_idx=Building_Nove_idx[np.where(Comp_Other[Building_Nove_idx]==1)[0]]
Building_Other_idx.shape

(1029,)

### Open_Sparse

In [24]:
Open_Sparse=np.load("/data/DW/Challenge/GermanAIChallenge2018/Round_2/SmallClass/building_scheme1/Open_Sparse/R2_preda_single_optionB_building_open_sparse_Res50_epoch40_fold1_0210_soft_nos1.npy")
np.unique(Open_Sparse)

array([0, 1])

In [25]:
Building_Open_idx=Building_Ve_idx[np.where(Open_Sparse[Building_Ve_idx]==0)[0]]
Building_Open_idx.shape

(760,)

In [26]:
Building_Sparse_idx=Building_Ve_idx[np.where(Open_Sparse[Building_Ve_idx]==1)[0]]
Building_Sparse_idx.shape

(387,)

### Compact

In [27]:
Comp=np.load("/data/DW/Challenge/GermanAIChallenge2018/Round_2/SmallClass/building_scheme1/Compact/R2_preda_single_optionB_building_comp_Res50_epoch66_fold1_0210_soft_nos1.npy")
np.unique(Comp)

array([0, 1, 2])

In [28]:
Result[Building_Comp_idx]=Comp[Building_Comp_idx]
np.unique(Result)

array([-1.,  0.,  1.,  2., 10., 11., 12., 13., 14., 15., 16.])

### Other

In [29]:
Other=np.load("/data/DW/Challenge/GermanAIChallenge2018/Round_2/SmallClass/building_scheme1/Other/R2_preda_single_optionB_building_other_Res50_epoch51_fold1_0210_soft_nos1.npy")
np.unique(Other)

array([0, 1, 2])

In [30]:
Other_labeled=-np.ones(Other.shape)
Other_labeled.shape

(4842,)

In [31]:
Other_labeled[Other==0]=6
Other_labeled[Other==1]=7
Other_labeled[Other==2]=9
np.unique(Other_labeled)

array([6., 7., 9.])

In [32]:
Result[Building_Other_idx]=Other_labeled[Building_Other_idx]
np.unique(Result)

array([-1.,  0.,  1.,  2.,  6.,  7.,  9., 10., 11., 12., 13., 14., 15.,
       16.])

### Open

In [33]:
Open=np.load("/data/DW/Challenge/GermanAIChallenge2018/Round_2/SmallClass/building_scheme1/Open/R2_preda_single_optionB_building_open_Res50_epoch35_fold1_0210_soft_nos1.npy")
np.unique(Open)

array([0, 1, 2])

In [34]:
Open_labeled=Open+3
np.unique(Open_labeled)

array([3, 4, 5])

In [35]:
Result[Building_Open_idx]=Open_labeled[Building_Open_idx]
np.unique(Result)

array([-1.,  0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  9., 10., 11., 12.,
       13., 14., 15., 16.])

### Sparse

In [36]:
print(np.unique(Open_Sparse[Building_Sparse_idx]))
Result[Building_Sparse_idx]=8
np.unique(Result)

[1]


array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16.])

## Save

In [37]:
import torch

In [38]:
def write_csv(results,file_name):
    import csv
    with open(file_name,'w') as f:
        writer = csv.writer(f)
        #writer.writerow(['id','label'])
        writer.writerows(results)#注意读写

#from keras.utils import to_categorical
#result = to_categorical(np.array(pred_y))


label=torch.from_numpy(Result[:,np.newaxis]).long()
print(label.shape)
one_hot=torch.zeros(len(Result), 17).scatter_(1, label, 1)
write_csv(one_hot.numpy().astype(int),'R2_preda_LSClass_single_optionB_Res50_0210_soft_nos1.csv')

torch.Size([4842, 1])
